require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Lint/MissingSuper:
  Enabled: false